### ISSUE TITLE
Handling of empty arrays

### ISSUE THREAD

**Issue by ndbabb** [brooklynDev/airborne#19]
I am using expect_json_types and expect_json and getting some unexpected results when testing with an empty array.

To illustrate, take the "test_responses/array_with_index.json" file and modify to be an empty array:

```
{
    "cars":[]
}
```

The following two expectations pass but I think they should be failing.

```
expect_json('cars.?', {make: 'Toyota'})
expect_json_types('cars.*', {some_key: :integer, name: :string})
```

**Comment by theodorton** [comment]
Sorry if closed issues are off-limits, but my application broke because `expect_json('cars.?',...)` didn't check for presence.

In retrospect I see how `expect_json_sizes` would solve the issue, but I would expect the `expect_json(...)` to actually test for presence.

What's the rationale behind passing expectations for empty arrays?
