### ISSUE TITLE
JSON::ParserError 757 on Post Success

### ISSUE THREAD

**Issue by dmhalejr** [brooklynDev/airborne#39]
Hello -- 

The post is successful, but the only return value I am receiving is `481973`.

Ran the call manually through the API and received only one integer value for response and I am not sure how to quantify that within the testing framework since there is no structure.

Manual Response: _(NOTE: the integer is different since they are all unique values)_
```
477877
```

Test:
```
  it 'should create a new field' do
    post "/fields", {shortcut_name: "#{Faker::Lorem.characters(10)}", display_name: "#{Faker::Lorem.characters(5)}", field_type: "text", widget_type: "text", column_order: 0}
  end
```

Gemfile:
```
faker (1.4.3)
airborne (0.1.11)
json (1.7.6)
```

Error:
```
  1) GET - Fields should create a new field
     Failure/Error: post "/fields", {shortcut_name: "#{Faker::Lorem.characters(10)}", display_name: "#{Faker::Lorem.characters(5)}", field_type: "text", widget_type: "text", column_order: 0}
     JSON::ParserError:
       757: unexpected token at '481973'
     # /Users/dhale/.rvm/gems/ruby-2.1.0/gems/json-1.7.6/lib/json/common.rb:155:in `parse'
     # /Users/dhale/.rvm/gems/ruby-2.1.0/gems/json-1.7.6/lib/json/common.rb:155:in `parse'
     # /Users/dhale/.rvm/gems/ruby-2.1.0/gems/airborne-0.1.11/lib/airborne/base.rb:82:in `set_response'
     # /Users/dhale/.rvm/gems/ruby-2.1.0/gems/airborne-0.1.11/lib/airborne/base.rb:32:in `post'
     # ./spec/api_spec.rb:52:in `block (2 levels) in <top (required)>'
```

Thanks for your assistance!

**Comment by brooklynDev** [comment]
So the issue is the following. `airborne` makes the hard assumption that your API will be returning JSON, and all the expectations are built around that. The offending line is here:

https://github.com/brooklynDev/airborne/blob/40a8106589a52a20ab406a7868d1243b1a0a899b/lib/airborne/base.rb#L82

I'm open to wrapping that up on a begin/rescue but then none of the expect_* stuff would work, so you'd only be left with the regular RSpec matchers. I'll make this commit soon.

**Comment by brooklynDev** [comment]
OK, I made the change. 

https://github.com/brooklynDev/airborne/commit/3e7a95714c826157641f1b4c18153be622d989f6

Good luck!
